In [1]:
import torch
import tiktoken

In [2]:
raw_text = "This is my dog Chico. "

In [3]:
tokenizer = tiktoken.get_encoding("gpt2")

In [4]:
enc_text = tokenizer.encode_ordinary( raw_text )
print( enc_text )

[1212, 318, 616, 3290, 609, 3713, 13, 220]


In [6]:
vocab_size = 5
output_dim = 4
inputs = torch.nn.Embedding( vocab_size, output_dim )
print(inputs.weight)

Parameter containing:
tensor([[-0.7386,  0.1657, -0.2903,  0.2391],
        [-0.0572,  2.1028,  0.8419, -0.5429],
        [ 0.6766, -0.2057,  1.0335,  1.8245],
        [ 1.7029, -0.5684, -1.3094,  0.5871],
        [ 1.4957,  1.4431,  0.7753, -0.0880]], requires_grad=True)


In [7]:
inputs = inputs.weight.data
inputs

tensor([[-0.7386,  0.1657, -0.2903,  0.2391],
        [-0.0572,  2.1028,  0.8419, -0.5429],
        [ 0.6766, -0.2057,  1.0335,  1.8245],
        [ 1.7029, -0.5684, -1.3094,  0.5871],
        [ 1.4957,  1.4431,  0.7753, -0.0880]])

In [8]:
inputs.shape

torch.Size([5, 4])

In [9]:
for row in inputs:
    print( row.tolist() )

[-0.7386221885681152, 0.16569848358631134, -0.2903316020965576, 0.23905405402183533]
[-0.057237159460783005, 2.102775812149048, 0.8418706059455872, -0.5428633689880371]
[0.6765967607498169, -0.20573462545871735, 1.033491849899292, 1.8245164155960083]
[1.702863097190857, -0.5684067010879517, -1.3093589544296265, 0.5870882272720337]
[1.4957441091537476, 1.443142294883728, 0.7753391861915588, -0.08796791732311249]


In [10]:
x = torch.tensor([1.1,2.3])
y = torch.tensor([3.4,-2.1])


In [11]:
torch.dot(x,y)

tensor(-1.0900)

In [12]:
query = inputs[2]
print( query )

tensor([ 0.6766, -0.2057,  1.0335,  1.8245])


In [13]:
for i in range(len(inputs)):
    print( torch.dot( query, inputs[i] ) )

tensor(-0.3977)
tensor(-0.5917)
tensor(4.8971)
tensor(0.9870)
tensor(1.3559)


In [16]:
attention_scores_2 = torch.zeros(len(inputs)) 
for i in range(len(inputs)):
    attention_scores_2[i] = torch.dot( query, inputs[i] )
print( attention_scores_2 )

tensor([-0.3977, -0.5917,  4.8971,  0.9870,  1.3559])


In [19]:
# normalize the attention scores using the softmax function
# def softmax(x):
#     torch.exp(x) / torch.exp(x).sum()

In [21]:
attention_scores_2 = torch.softmax(attention_scores_2, dim=0)
attention_scores_2

tensor([0.0047, 0.0039, 0.9450, 0.0189, 0.0274])

In [22]:
attention_scores_2.sum()

tensor(1.)

In [23]:
context_vector_2 = torch.zeros( query.shape )
for i in range(len(attention_scores_2)):
    context_vector_2 += attention_scores_2[i] * inputs[i]
context_vector_2

tensor([ 0.7089, -0.1567,  0.9750,  1.7319])