In [1]:
import torch
import torch.nn as nn

In [6]:
outputs = torch.randn(3,6)
outputs 

tensor([[ 0.7971, -2.5684,  1.7885, -0.8256,  1.8479, -1.0657],
        [ 0.3200, -0.1428, -1.1862, -2.0696,  0.5006, -0.1100],
        [-0.5259, -1.5950,  0.9015, -0.8280, -1.9244,  1.3996]])

In [7]:
outputs.mean( dim=1, keepdim=True )

tensor([[-0.0044],
        [-0.4480],
        [-0.4287]])

In [8]:
outputs.std( dim=1, keepdim=True )

tensor([[1.7699],
        [0.9871],
        [1.3325]])

In [9]:
torch.set_printoptions( sci_mode=False )

In [ ]:
class LayerNorm1d(nn.Module):
    def __init__(self, emb_dim):
        super.__init__()
        