In [1]:
import torch 
import torch.nn as nn

In [2]:
# one way to make some typical input:
input = torch.randn(1, 3)
input

tensor([[ 0.2752, -0.0121,  0.4787]])

In [3]:
input = torch.tensor([[1.0, 2.0, 3.0]])
input

tensor([[1., 2., 3.]])

In [4]:
# a simple neural network with one hidden layer
model = nn.Sequential(
    nn.Linear(3, 2),  # input layer to hidden layer, take 3 inputs, output 2 values
    nn.ReLU(),        # a nonlinear activation function
    nn.Linear(2, 1)   # hidden layer to output layer, take 2 inputs, output 1 value
)

In [5]:
model[0].weight.data = torch.tensor([[2.0, 1.0, -1.0],
                                     [-2.4, -1.0, 1.0]])
model[0].weight.data

tensor([[ 2.0000,  1.0000, -1.0000],
        [-2.4000, -1.0000,  1.0000]])

In [6]:
model[0].bias.data = torch.tensor([0.0, 0.0])

In [7]:
input @ model[0].weight.T + model[0].bias.data

tensor([[ 1.0000, -1.4000]], grad_fn=<AddBackward0>)

In [8]:
activation = nn.ReLU()
middle = activation(input @ model[0].weight.data.T + model[0].bias.data)
middle

tensor([[1., 0.]])

In [9]:
middle @ model[2].weight.data.T + model[2].bias.data

tensor([[0.6910]])

In [10]:
model(input)

tensor([[0.6910]], grad_fn=<AddmmBackward0>)